name: cleaner_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.1+22

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.7.1
  path_provider: ^2.1.5
  crypto: ^3.0.3
  system_info2: 4.1.0
  image: ^4.5.4
  disk_space: ^0.2.1
  cupertino_icons: ^1.0.8
  animated_text_lerp: ^2.0.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  provider: ^6.1.5+1
  flutter_card_swiper: ^7.0.2

  video_compress: ^3.1.3
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: 9.0.0
  photo_manager_image_provider: ^2.2.0
  sentry_flutter: ^9.6.0
  flutter_contacts: ^1.1.9+2
  in_app_review: ^2.0.9
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  purchases_flutter: 8.5.2
  another_flushbar: ^1.12.32
  dio: ^5.9.0
  ip_country_lookup: ^1.0.3
  lottie: ^3.3.2
  device_info_plus: ^12.1.0
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo/app_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo/
    - lib/assets/images/
    - lib/assets/animation/
