// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxKPIyZ9dWiSHHEGsp8tSbhSPQv0-ivHg',
    appId: '1:673491911123:android:026a0a3e334e07244d2f26',
    messagingSenderId: '673491911123',
    projectId: 'mobile-base-121fe',
    storageBucket: 'mobile-base-121fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEqx56mV-QD-AxpxkZYBqqXGlYCw8hv20',
    appId: '1:673491911123:ios:d89d73b6130a93cb4d2f26',
    messagingSenderId: '673491911123',
    projectId: 'mobile-base-121fe',
    storageBucket: 'mobile-base-121fe.firebasestorage.app',
    iosBundleId: 'com.example.mobilebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoXBzMOgelTdVdr9irmxrWYyXtIsh6UM',
    appId: '1:673491911123:web:4397606dc9d03a1c4d2f26',
    messagingSenderId: '673491911123',
    projectId: 'mobile-base-121fe',
    authDomain: 'mobile-base-121fe.firebaseapp.com',
    storageBucket: 'mobile-base-121fe.firebasestorage.app',
    measurementId: 'G-WR2DXD6SML',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEqx56mV-QD-AxpxkZYBqqXGlYCw8hv20',
    appId: '1:673491911123:ios:d89d73b6130a93cb4d2f26',
    messagingSenderId: '673491911123',
    projectId: 'mobile-base-121fe',
    storageBucket: 'mobile-base-121fe.firebasestorage.app',
    iosBundleId: 'com.example.mobilebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEoXBzMOgelTdVdr9irmxrWYyXtIsh6UM',
    appId: '1:673491911123:web:0d8a11d830b98db14d2f26',
    messagingSenderId: '673491911123',
    projectId: 'mobile-base-121fe',
    authDomain: 'mobile-base-121fe.firebaseapp.com',
    storageBucket: 'mobile-base-121fe.firebasestorage.app',
    measurementId: 'G-RT7RTJ7J17',
  );

}